version: '3.9'
services:
  backend:
    image: node:16-alpine
    command: npm run start:dev
    restart: on-failure
    working_dir: /app/backend
    volumes:
      - .:/app/backend
    ports:
      - 3000:3000
      - 50051:50051
    tty: true
    # depends_on:
    #   db:  # mysql ou postgres
    #     condition: service_healthy
    # environment:
    #   - PORT=${PORT}
    #   - DB_USER=${DB_USER}
    #   - DB_PASS=${DB_PASSWORD}
    #   - DB_HOST=db  # mysql ou postgres
    #   - DB_NAME=${DB_DATABASE}
    #   - DB_PORT=${DB_PORT}
    # healthcheck:
    #   test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
    #   timeout: 10s
    #   retries: 5
