version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    command: npm run start:dev
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - 3000:${PORT}
      - 50051:50051
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - GRPC_URL=backend:50051

      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - MONGO_URI=mongodb://mongo:27017/${DB_NAME}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASS=${MAILER_PASS}

      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:${RABBITMQ_PORT}
    networks:
      - personal-network

  postgres:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 30s
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
    networks:
      - personal-network

  mongo:
    image: mongo:5.0.7
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
    networks:
      - personal-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_ERLANG_COOKIE=SQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - personal-network

networks:
  personal-network:
    name: personal-network
    driver: bridge
