FROM node:16-alpine AS installer

WORKDIR /app

COPY ../package.*json ./

RUN npm ci


FROM node:16-alpine AS builder

WORKDIR /app

COPY --from=installer /app/node_modules ./node_modules
COPY .. .

RUN npx prisma generate
RUN npm run build


FROM node:16-alpine As runner

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json

CMD ["npm", "run", "start:prod"]
