FROM node:22-alpine AS installer

WORKDIR /app

COPY package*.json .

RUN npm install


FROM node:22-alpine AS runner

WORKDIR /app

EXPOSE 3000

COPY --from=installer /app/node_modules ./node_modules
COPY . .

CMD ["npm", "run", "start:dev"]
