on: [pull_request]

jobs:
  Automatic-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Verify git repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: automatic-tests-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-automatic-tests-cache--build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node on version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        if: steps.automatic-tests-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm run test


  Coverage:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

      mongo:
        image: mongo:5.0.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      # - uses: ArtiomTr/jest-coverage-report-action@v2
      #   id: coverage
      #   with:
      #     test-script: npm run test:cov
      #     output: report-markdown

      - name: Install node on version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache node_modules
        id: coverage-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-coverage-cache--build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests and generate coverage
        run: npm run test:cov
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/database
          MONGO_URI: mongodb://localhost:27017/database

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-artifact
          path: ./coverage/test-report.xml

      # - uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     message: ${{ steps.coverage.outputs.report }}


  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [Automatic-Tests, Coverage]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-artifact
          path: coverage

      # - name: Install node on version
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16

      # - name: Cache node_modules
      #   id: my-cache
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      # - name: Install dependencies
      #   if: steps.my-cache.outputs.cache-hit != 'true'
      #   run: npm ci

      # - name: Test coverage generation
      #   run: npm run test:cov
      #   env:
      #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/database
      #     MONGO_URI: mongodb://mongo:27017/database

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
