on:
  pull_request:
      branches:
        - dev


jobs:
  Automatic-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Verify git repository
        uses: actions/checkout@v3

      - name: Install node on version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  Coverage:
    runs-on: ubuntu-latest
    needs: Automatic-Tests

    services:
      postgres:
        image: postgres:14.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

      mongo:
        image: mongo:5.0.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage report
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/database
          MONGO_URI: mongodb://localhost:27017/database
        run: npm run test:cov

      - name: Comment coverage on PR
        uses: romeovs/lcov-reporter-action@v0.2.16
